# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Dawn\'s site'
tagline:          'A test site for learning'
description:      'A description goes here.'
url:              
baseurl:          /dawnc/

author:
  name:           'Childress'
  url:            https://dawnchildress.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/collectionslab/dawnc
